.Dd 02 Apr 2026
.Dt sbocutleaves 1
.Os sbotools
.Sh NAME
.Nm sbocutleaves
.Nd remove leaf packages
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
finds leaf packages (those which no other packages require) installed from
slackbuilds.org, offers to remove or keep them, and repeats this process until
no leaf packages are marked for deletion.
.Sh SEE ALSO
.Xr removepkg 8

