.TH sboconfig 1 "Setting Orange, Discord 57, 3191 YOLD" "sbotools 3.6" sbotools
.SH NAME
.P
.B
sboconfig
- set
.B
sbotools
configuration options
.SH SYNOPSIS
.P
sboconfig [-h|-v]
.P
sboconfig [-l]
.P
sboconfig [--reset]
.P
sboconfig [-C TRUE|FALSE] [-c TRUE|FALSE] [-d TRUE|FALSE] \\
          [-g TRUE|FALSE ] [-j #|FALSE] [-P TRUE|FALSE] \\
          [-p /path|FALSE] [-s /path|/usr/sbo] [-B branch_name|FALSE] \\
          [-b TRUE|FALSE] [-O TRUE|FALSE] [-o /path|FALSE] \\
          [-V #.#|FALSE] [-r url|FALSE] [-R TRUE|FALSE] \\
          [-S TRUE|FALSE]
.SH DESCRIPTION
.P
.B
sboconfig
is a front-end for managing
.B
sbotools
configuration options. Using
.B
sboconfig
without any flags starts an interactive menu
to specify settings; all options are accompanied by
an explanatory message, and no changes are applied
without user confirmation.
.P
The
.B
sbotools.conf(5)
file can also be manually edited; any fields not
relevant to
.B
sbotools
configuration are ignored.
.P
Non-root users can only call
.B
sboconfig
with the
.B
--list\fR\
\&,
.B
--help
and
.B
--version
flags.
.SH OPTIONS
.P
.B
-h|--help
.RS
Show help information.
.RE
.P
.B
-v|--version
.RS
Show version information.
.RE
.P
.B
-l|--list
.RS
List the current configuration options, including
unmodified defaults.
.B
--list
also shows the
.B
sboconfig
flag used to set each option for reference. The
.B
--list
flag can be used without root privileges.
.RE
.P
.B
--reset
.RS
Restore the default configuration to
.I
/etc/sbotools/sbotools.conf\fR\
\&.
.RE
.P
.B
-B|--branch (FALSE|branch_name)
.RS
.B
GIT_BRANCH\fR\
\&: If
.B
FALSE\fR\
\&, use the default git branch for the Slackware
version, if any. If
.B branch_name\fR\
\&, attempt to change
branches to
.B
branch_name
when using
.B
sbocheck(1)
with an upstream git repository.
.RE
.P
.B
-b|--build-ignore (FALSE|TRUE)
.RS
.B
BUILD_IGNORE\fR\
\&: If
.B
TRUE\fR\
\&, do not perform upgrades unless the
version number differs. By default, upgrades
also occur when the build number differs.
.RE
.P
.B
-C|--classic (FALSE|TRUE)
.RS
.B
CLASSIC\fR\
\&: If
.B
TRUE\fR\
\&, automatically enable
.B
RSYNC_DEFAULT
and
.B
BUILD_IGNORE
(overriding the contents of
.B
sbotools.conf(5)\fR\
). Build increment and out-of-tree SlackBuild
checks by
.B
sbocheck(1)
are disabled, and previously-used build options are not displayed.
This provides a more traditional
.B
sbotools
look and feel for those who want it.
.RE
.P
.B
-c|--noclean (FALSE|TRUE)
.RS
.B
NOCLEAN\fR\
\&: If
.B
TRUE\fR\
\&, do not clean working directories after building.
These are the build and
.I
package-(sbo)
directories under
.I
/tmp/SBo
(or
.I
$TMP\fR\
\&).
.RE
.P
.B
-d|--distclean (FALSE|TRUE)
.RS
.B
DISTCLEAN\fR\
\&: If
.B
TRUE\fR\
\&, remove the package and source archives after building. Source
archives are otherwise retained in md5sum-designated directories under
.I
/usr/sbo/distfiles
(with default
.B
SBO_HOME\fR\
\&). If
.B
PKG_DIR
is set, package archives are saved there regardless of
.B
DISTCLEAN\fR\
\&.
.RE
.P
.B
-g|--gpg-verify (FALSE|TRUE)
.RS
.B
GPG_VERIFY\fR\
\&: If
.B
TRUE\fR\
\&, use
.B
gpg
to verify the contents of the local repository (and, if applicable,
.I
/etc/sbotools/obsolete\fR\
) when running
.B
sbocheck(1)\fR\
\&,
.B
sboinstall(1)
and
.B
sboupgrade(1)\fR\
\&. Missing public keys are detected, and a download from
.UR keyserver.ubuntu.com
.UE
on port 80 is offered if available.
Only rsync repositories can be verified on Slackware 14.0 and Slackware 14.1.
.RE
.P
.B
-j|--jobs (FALSE|#)
.RS
.B
JOBS\fR\
\&: If
.B
numerical\fR\
\&, pass to the
.B
-j
argument when a SlackBuild invoking
.B
make
is run.
.RE
.P
.B
-P|--cpan-ignore (FALSE|TRUE)
.RS
.B
CPAN_IGNORE\fR\
\&: If
.B
TRUE\fR\
\&, install scripts even if they are already installed from the CPAN.
.RE
.P
.B
-O|--obsolete-check (FALSE|TRUE)
.RS
.B
OBSOLETE_CHECK\fR\
\&: If
.B
TRUE\fR\
\&, download an updated copy of the obsolete script list to
.I
/etc/sbotools/obsolete
from the
.B
sbotools
home page at
.UR https://pghvlaans.github.io/sbotools
.UE
when running
.B
sbocheck(1)
in Slackware -current.
.RE
.P
.B
-p|--pkg-dir (FALSE|/path)
.RS
.B
PKG_DIR\fR\
\&: If set to a
.B
path\fR\
\&, packages are stored there after installation. This
overrides the
.B
DISTCLEAN
setting for saved packages.
.RE
.P
.B
-s|--sbo-home (/usr/sbo|/path)
.RS
.B
SBO_HOME\fR\
\&: If set to a
.B
path\fR\
\&, this is where the
.B
SlackBuilds.org
tree is stored. The default setting is
.I
/usr/sbo\fR\
\&. The tree must be re-downloaded if the
.B
SBO_HOME
setting changes.
.RE
.P
.B
-o|--local-overrides (FALSE|/path)
.RS
.B
LOCAL_OVERRIDES\fR\
\&: If set to a
.B
path\fR\
\&, any directory name in the top level under that path matching a
SlackBuild name is used in preference to the
in-tree version. This works even if the SlackBuild
is out-of-tree. Scripts installing packages not marked
with the
.I
_SBo
tag are neither upgradeable with
.B
sboupgrade(1)
nor removable with
.B
sboremove(1)\fR\
\&.
.I
README\fR\
\&,
.I
slack-desc\fR\
\&, an
.I
info\fR\
 file and a SlackBuild must all be present.
.RE
.P
.B
-V|--slackware-version (FALSE|#.#)
.RS
.B
SLACKWARE_VERSION\fR\
\&: If set to a
.B
version number\fR\
\&, use the
.B
SlackBuilds.org
repository for that version of Slackware rather than
the one specified in
.I
/etc/slackware-version\fR\
\&.
.RE
.P
.B
-r|--repo (FALSE|url)
.RS
.B
REPO\fR\
\&: If set to a git or rsync
.B
URL\fR\
\&, use that repository instead of the
.B
sbotools
default for your
.B
SLACKWARE_VERSION\fR\
\&. The default repositories are under
.UR rsync://slackbuilds.org/slackbuilds
.UE
if
.B
RSYNC_DEFAULT
is
.B
TRUE
and for Slackware versions prior to 14.2, and
.UR https://gitlab.com/SlackBuilds.org
.UE
otherwise. The repository must be laid out in the same
manner as one found at
.UR https://git.slackbuilds.org/slackbuilds
.UE
such that SlackBuild directories are under the
category directories.
.RE
.P
.B
-R|--rsync (FALSE|TRUE)
.RS
.B
RSYNC_DEFAULT\fR\
\&: If set to
.B
TRUE\fR\
\&, use rsync default mirrors except for Slackware -current.
.RE
.P
.B
-S|--strict-upgrades (FALSE|TRUE)
.RS
.B
STRICT_UPGRADES\fR\
\&: If set to
.B
TRUE\fR\
\&, upgrades are only attempted if the incoming
version or build number is greater. This has no
effect on scripts in the local overrides directory.
.RE
.SH EXIT CODES
.P
.B
sboconfig
can exit with the following codes:
.RS

0: all operations were successful.
.RE
.RS
1: a usage error occurred (e.g. passing invalid option specifications)
.RE
.RS
2: a script or module error occurred.
.RE
.RS
6:
.B
sboconfig
was unable to obtain a required file handle.
.RE
.SH BUGS
.P
None known. If found, Issues and Pull Requests to
.UR https://github.com/pghvlaans/sbotools/
.UE
are always welcome.
.SH SEE ALSO
.P
sbocheck(1), sboclean(1), sbofind(1), sbohints(1), sboinstall(1), sboremove(1), sboupgrade(1), sbotools.conf(5), sbotools.hints(5)
.SH AUTHORS
.P
Jacob Pipkin <j@dawnrazor.net>
.P
Luke Williams <xocel@iquidus.org>
.P
Andreas Guldstrand <andreas.guldstrand@gmail.com>
.SH MAINTAINER
.P
K. Eugene Carlson <kvngncrlsn@gmail.com>
