.TH sboclean 1 "Prickle-Prickle, Chaos 29, 3191 YOLD" "sbotools 3.4.1" sbotools
.SH NAME
.P
.B
sboclean
- clean files left by
.B
sbotools
.SH SYNOPSIS
.P
sboclean [-h|-v]
.P
sboclean [-dwi] [-o ALL|package]
.SH DESCRIPTION
.P
.B
sboclean
is used to clean files left by
.B
sbotools\fR\
\&,
such as saved options (in
.I
/var/log/sbotools\fR\
\&), downloaded source files (\(lqdistfiles\(rq), or
working directories under
.I
/tmp/SBo
(or
.I
$TMP\fR\
\&) and, for compat32 installs, under
.I
/tmp
(or
.I
$TMP\fR\
\&). Note that if not run with the
.B
--interactive
flag,
.B
sboclean
removes anything in the distfiles and/or
.I
/tmp/SBo
(or
.I
$TMP\fR\
\&) directories and any
.I
/tmp/package-*-compat32
(or
.I
$TMP/package-*-compat32\fR\
\&) directories with extreme prejudice. One of
.B
--dist\fR\
,
.B
--work
or
.B
--option
must be specified for this script to do anything.
.P
If an invalid configuration is detected in
.I
/etc/sbotools/sbotools.conf\fR\
\&, the script exits with a diagnostic message.
.SH OPTIONS
.P
.B
-h|--help
.RS
Show help information.
.RE
.P
.B
-v|--version
.RS
Show version information.
.RE
.P
.B
-d|--dist
.RS
Clean distfiles, located at
.I
/usr/sbo/distfiles
by default.
.RE
.P
.B
-w|--work
.RS
Clean working directories, located by default under
.I
/tmp/SBo
and, for compat32 installs,
.I
/tmp\fR\
\&.
.RE
.P
.B
-o|--options (ALL|sbo_name)
.RS
With
.B
ALL\fR\
\&, clean all saved options from
.I
/var/log/sbotools\fR\
\&. With the name of a SlackBuild, clean the saved
options for that SlackBuild only.
.RE
.P
.B
-i|--interactive
.RS
Be interactive;
.B
sboclean
uses confirmation prompts for each item that could be
removed.
.SH EXIT CODES
.P
.B
sboclean
can exit with the following codes:
.RS

0: all operations completed successfully.
.RE
.RS
1: a usage error occurred, such as running
.B
sboclean
with nothing to clean.
.RE

.SH BUGS
.P
None known. If found, Issues and Pull Requests to
.UR https://github.com/pghvlaans/sbotools/
.UE
are always welcome.
.SH SEE ALSO
.P
sbocheck(1), sboconfig(1), sbofind(1), sbohints(1), sboinstall(1), sboremove(1), sboupgrade(1), sbotools.conf(5), sbotools.hints(5)
.SH AUTHORS
.P
Jacob Pipkin <j@dawnrazor.net>
.P
Luke Williams <xocel@iquidus.org>
.P
Andreas Guldstrand <andreas.guldstrand@gmail.com>
.SH MAINTAINER
.P
K. Eugene Carlson <kvngncrlsn@gmail.com>
