.TH sbocheck 1 "Prickle-Prickle, The Aftermath 62, 3190 YOLD" "sbotools 3.2.1" sbotools
.SH NAME
.P
.B
sbocheck
- update a local
.B
slackbuilds.org
tree and check for updates
.SH SYNOPSIS
.P
sbocheck [-h|-v]
.P
sbocheck [-g|-n]
.SH DESCRIPTION
.P
.B
sbocheck
first updates a previously-fetched copy of the
.B
slackbuilds.org
tree (see
.B
sbosnap(1)\fR\
\&), checks for available upgrades, and reports what it finds.
SlackBuilds with differing build numbers are reported separately,
as are any SlackBuilds marked
.I
_SBo
that are not found in the
repository or local overrides (see
.B
sboconfig(1)
or
.B
sbotools.conf(5)\fR\
).
.P
The three output categories are logged separately to
.I
/etc/sbocheck.log\fR\
\&,
.I
/etc/sbocheck-bumps.log
and
.I
/etc/sbocheck-out-of-tree.log\fR\
\&. The out-of-tree and build number increment checks are disabled
when
.B
CLASSIC
is
.B
TRUE
(see
.B
sboconfig(1)
or
.B
sbotools.conf(5)\fR\
).
.P
To check for updated SlackBuilds without updating the SlackBuilds
tree, pass
the
.B
--nopull
option.
.B
sbocheck
will perform
.B
gpg
verification upon pulling the tree if
.B
GPG_VERIFY
is
.B
TRUE
(see
.B
sboconfig(1)
or
.B
sbotools.conf(5)\fR\
). The 
.B
--gpg-verify
option has the same effect. Passing both
.B
--gpg-verify
and
.B
--nopull
verifies the repo in-place without fetching.
Only rsync repositories can be verified on Slackware 14.0 and Slackware 14.1.
.P
If an invalid configuration is detected in
.I
/etc/sbotools/sbotools.conf\fR\
\&, the script will exit with a diagnostic message.
.SH OPTIONS
.P
.B
-g|--gpg-verify
.RS
Use
.B
gpg
to verify the fetched repository, even if
.B
GPG_VERIFY
is
.B
FALSE\fR\
\&. When called with
.B
--nopull\fR\
\&, verify the repo without fetching.
Only rsync repositories can be verified on Slackware 14.0 and Slackware 14.1.
.RE
.P
.B
-n|--nopull
.RS
Check for updated SlackBuilds without updating the SlackBuilds
tree.
.RE
.P
.B
-h|--help
.RS
Show help information.
.RE
.P
.B
-v|--version
.RS
Show version information.
.RE
.SH BUGS
.P
None known. If found, Issues and Pull Requests to
.UR https://github.com/pghvlaans/sbotools/
.UE
are always welcome.
.SH SEE ALSO
.P
sboclean(1), sboconfig(1), sbofind(1), sboinstall(1), sboremove(1), sbosnap(1), sboupgrade(1), sbotools.conf(5), sbotools.hints(5)
.SH AUTHORS
.P
Jacob Pipkin <j@dawnrazor.net>
.P
Luke Williams <xocel@iquidus.org>
.P
Andreas Guldstrand <andreas.guldstrand@gmail.com>
.SH MAINTAINER
.P
K. Eugene Carlson <kvngncrlsn@gmail.com>
