.TH sbofind 1 "Pungenday, Discord 5, 3191 YOLD - Mojoday" "sbotools 3.5_RC" sbotools
.SH NAME
.P
.B
sbofind
- search the local copy of the
.B
SlackBuilds.org
tree for a given name or names
.SH SYNOPSIS
.P
sbofind [-h|-v]
.P
sbofind [-EetiRrq] search_term (search_term)
.SH DESCRIPTION
.P
.B
sbofind
searches the names of all available SlackBuilds for one or more
search terms. It reports back any SlackBuilds found along
with path and version information. This is equivalent to
running
.RS

cd /usr/ports; make search name=$search_term display=name,path


.RE
on a FreeBSD system. If the repository includes a
.I
TAGS.txt
file, these tags are searched to generate additional results.
.P
Non-root users can call
.B
sbofind
with any flags. If an invalid configuration is detected in
.I
/etc/sbotools/sbotools.conf\fR\
\&, the script exits with a diagnostic message.
.SH OPTIONS
.P
.B
-h|--help
.RS
Show help information.
.RE
.P
.B
-v|--version
.RS
Show version information.
.RE
.P
.B
-E|--exact-case
.RS
Exact matching only (case-sensitive).
.RE
.P
.B
-e|--exact
.RS
Exact matching only (case-insensitive).
.RE
.P
.B
-t|--no-tags
.RS
Exclude tags from the search.
.RE
.P
.B
-i|--info
.RS
Show the contents of the
.I
info
file for each SlackBuild found.
.RE
.P
.B
-r|--readme
.RS
Show the contents of the
.I
README
file for each SlackBuild found.
.RE
.P
.B
-R|--reverse
.RS
Show any reverse dependencies installed on the system.
Please note that optional dependencies must be specified in
.B
sbotools.hints(5)
to be included. Packages with tags other than
.I
_SBo
are not included.
.RE
.P
.B
-q|--queue
.RS
Show the build queue for each SlackBuild found given the contents
of
.I
/etc/sbotools/sbotools.hints\fR\
\&.
.RE
.SH EXIT CODES
.P
.B
sbofind
can exit with the following codes:
.RS

0: all operations were succesful.
.RE
.RS
1: a usage error occured (e.g., incorrect options were passed to
.B
sbofind
).
.RE
.RS
6:
.B
sbofind
was unable to obtain a required file handle.
.RE
.RS
13: circular dependencies detected.
.RE
.SH BUGS
.P
None known. If found, Issues and Pull Requests to
.UR https://github.com/pghvlaans/sbotools/
.UE
are always welcome.
.SH SEE ALSO
.P
sbocheck(1), sboclean(1), sboconfig(1), sbohints(1), sboinstall(1), sboremove(1), sboupgrade(1), sbotools.conf(5), sbotools.hints(5)
.SH AUTHORS
.P
Jacob Pipkin <j@dawnrazor.net>
.P
Luke Williams <xocel@iquidus.org>
.P
Andreas Guldstrand <andreas.guldstrand@gmail.com>
.SH MAINTAINER
.P
K. Eugene Carlson <kvngncrlsn@gmail.com>
