.TH sbohints 1 "Pungenday, Chaos 38, 3191 YOLD" "sbotools 3.4.2" sbotools
.SH NAME
.P
.B
sbohints
- interact with sbotools.hints
.SH SYNOPSIS
.P
sbohints [-h | -v]
.P
sbohints [-l | --reset]
.P
sbohints [-c] [-b | -o | -O] sbo_name (sbo_name)
.P
sbohints [-q] sbo_name (sbo_name)
.SH DESCRIPTION
.P
.B
sbohints
is a script for querying and editing the blacklist
and optional dependency requests made in
.B
sbotools.hints(5)\fR\
\&. The modification flags are
.B
--blacklist\fR\
\&,
.B
--optional
and
.B
--replace-optional\fR\
\&. These can be used in conjunction with
.B
--clear\fR\
\&, but not with each other.
.P
Non-root users can only call
.B
sbohints
with the
.B
--list\fR\
\&,
.B
--query\fR\
\&,
.B
--help
and
.B
--version
flags. If an invalid configuration is detected in
.I
/etc/sbotools/sbotools.conf\fR\
\&, the script exits with a diagnostic message.
.SH OPTIONS
.P
.B
-b|--blacklist
.RS
Modify the blacklist by adding (or, with
.B
--clear\fR\
\&, clearing) one or more scripts.
.RE
.P
.B
-o|--optional
.RS
Add (or clear with
.B
--clear\fR\
\&) optional dependency requests for one or more
scripts. The current optional dependencies are displayed
together with a prompt for adding or clearing.
.RE
.P
.B
-O|--replace-optional
.RS
Replace all existing optional dependency requests for
one or more scripts. The current optional dependencies
are displayed together with a prompt for the new request
list. If used with
.B
--clear\fR\
\&, a confirmation prompt for clearing the optional
dependencies appears.
.RE
.P
.B
-c|--clear
.RS
This flag is used together with one (and only one) of
.B
--blacklist\fR\
\&,
.B
--optional
or
.B
--replace-optional\fR\
\&. For
.B
--blacklist
and
.B
--optional\fR\
\&, clear entries instead of adding them. For
.B
--replace-optional\fR\
\&, clear all existing optional dependency requests.
.RE
.P
.B
-l|--list
.RS
List the current blacklist and all optional dependency
requests. If a blacklisted script has optional dependency
requests or is requested as an optional depenedency, the
user is notified. The
.B
--list
flag can be used without root privileges.
.RE
.P
.B
-q|--query
.RS
Return the current blacklist and optional dependency request
status for one or more scripts. There is no output unless the
queried script is blacklisted, has optional dependency
requests or is on an optional dependency request list. The
.B
--query
flag can be used without root privileges.
.RE
.P
.B
--reset
.RS
Clear the blacklist and all optional dependency requests upon
confirmation.
.RE
.P
.B
-h|--help
.RS
Show help information.
.RE
.P
.B
-v|--version
.RS
Show version information.
.RE
.SH EXIT CODES
.P
.B
sbohints
can exit with the following codes:
.RS

0: all operations were successful.
.RE
.RS
1: a usage error occurred.
.RE
.RS
6:
.B
sbohints
was unable to obtain a required file handle.
.RE
.SH BUGS
.P
None known. If found, Issues and Pull Requests to
.UR https://github.com/pghvlaans/sbotools/
.UE
are always welcome.
.SH SEE ALSO
.P
sbocheck(1), sboclean(1), sboconfig(1), sbofind(1), sboinstall(1), sboremove(1), sboupgrade(1), sbotools.conf(5), sbotools.hints(5)
.SH AUTHORS
.P
Jacob Pipkin <j@dawnrazor.net>
.P
Luke Williams <xocel@iquidus.org>
.P
Andreas Guldstrand <andreas.guldstrand@gmail.com>
.SH MAINTAINER
.P
K. Eugene Carlson <kvngncrlsn@gmail.com>

