.TH sboinstall 1 "Setting Orange, The Aftermath 15, 3190 YOLD" "sbotools 3.0" sbotools
.SH NAME
.P
.B
sboinstall
- install SlackBuilds
.SH SYNOPSIS
.P
sboinstall [-h|-v]
.P
sboinstall [-d TRUE|FALSE] [-j #|FALSE] [-c TRUE|FALSE] \\
           [-ipRr] [--create-template FILE] sbo_name (sbo_name)
.P
sboinstall [-d TRUE|FALSE] [-j #|FALSE] [-c TRUE|FALSE] \\
           [-i] --use-template FILE
.SH DESCRIPTION
.P
.B
sboinstall
is used to install SlackBuilds. If the
.B
-r
flag is not specified,
.B
sboinstall
will pull the list of requirements from the
.I
info
file for any specified SlackBuild. This is a recursive
operation over all dependencies.
.B
sboinstall
will offer to install any non-installed dependencies in
the build queue. This program will not handle circular
dependencies.
.P
.I
README
files are parsed for
.B
groupadd
and
.B
useradd
commands, and
.B
sboinstall
will offer to run them prior to building. If the
.I
README
is judged to document options in
.I
KEY=VALUE
form, a prompt for setting options will appear. Any
build options, whether passed interactively or in a
template, will be saved to
.I
/var/log/sbotools
when the SlackBuild runs.
.P
Please note that saved build options will not be displayed
when
.B
CLASSIC
is set to
.B
TRUE\fR\
\&. See
.B
sboconfig(1)
or
.B
sbotools.conf(5)\fR\
\&.
.P
.B
sboinstall
will attempt to download the sources from the
.I
DOWNLOAD
or
.I
DOWNLOAD_x86_64
variables in the
.I
info
file. If
either the download or the md5sum check fails, a new
download will be attempted from
.UR ftp://slackware.uk/sbosrcarch/
.UE
as a fallback measure.
.SH OPTIONS
.P
.B
-h|--help
.RS
Show help information.
.RE
.P
.B
-v|--version
.RS
Show version information.
.RE
.P
.B
-c|--noclean (FALSE|TRUE)
.RS
If
.B
TRUE\fR\
\&, do not clean working directories after building.
These are the build and
.I
package-(sbo)
directories under
.I
/tmp/SBo
(or
.I
$TMP\fR\
). Cleaning these directories can be set as default
via the
.B
sboconfig(1)
command. See also
.B
sbotools.conf(5)\fR\
\&. This option overrides the default.
.RE
.P
.B
-d|--distclean (FALSE|TRUE)
.RS
If
.B
TRUE\fR\
\&, then remove the source archives after building. They
are retained in
.I
SBO_HOME/distfiles
by default. The package archive (in
.I
/tmp
by default) will also be removed. This option can be set
as default via the
.B
sboconfig(1)
command. See also
.B
sbotools.conf(5)\fR\
\&. This option overrides the default.
.RE
.P
.B
-i|--noinstall
.RS
Do not install the package at the end of the build process.
It will be left in
.I
/tmp
(or
.I
$OUTPUT\fR\
) if
.B
DISTCLEAN
is
.B
FALSE\fR\
\&. Packages are retained in
.B
PKG_DIR
if so defined regardless of
.B
DISTCLEAN\fR\
\&. See
.B
sboconfig(1)
and
.B
sbotools.conf(5)\fR\
\&.
.RE
.P
.B
-j|--jobs (FALSE|#)
.RS
If
.B
numerical\fR\
\&, pass to the
.B
-j
argument when a SlackBuild invoking
.B
make
is run.
.RE
.P
.B
-p|--compat32
.RS
Create a compat32 package on multilib x86_64 systems.
This requires the
.B
compat32-tools
package by Eric Hameleers. Please note that this operation
is not necessarily foolproof, and is unsupported by anyone
in principle. As a best practice,
.B
--compat32
should be combined with
.B
--noinstall
so that the contents of the package can be inspected prior
to installation. If the base package and compat32 package
are to be built at the same time, ensure that the
.B
DISTCLEAN
option is set to
.B
FALSE.
GitHub Issues are welcome in case of unexpected failure.
.RE
.P
.B
-r|--nointeractive
.RS
Bypass all user prompts and all dependency resolution for
the requested SlackBuilds. Unless it is obvious that dependency
resolution and build options are not required, consider using
a template instead.
.RE
.P
.B
-R|--norequirements
.RS
Bypass dependency resolution, but still show
.I
README
and the
user prompts before proceeding with the build.
.RE
.P
.B
--reinstall
.RS
Offer to reinstall all packages in the build queue.
.RE
.P
.B
--create-template (FILE)
.RS
Create a template for one or more SlackBuilds including any
pre-build commands and build options and save to the specified
.B
FILE\fR\
\&.
.RE
.P
.B
--use-template (FILE)
.RS
Build using the template saved to
.B
FILE.
This disables all user prompts.
.RE
.SH EXIT CODES
.P
.B
sboinstall
can exit with the following codes:
.RS

0: all operations were succesful.
.RE
.RS
1: a usage error occured, such as specifying invalid options.
.RE
.RS
3: a SlackBuild exited non-zero.
.RE
.RS
4: unable to md5sum verify the source file(s).
.RE
.RS
5: unable to download the source file(s).
.RE
.RS
6: unable to obtain a required file handle.
.RE
.RS
7: unable to get required info from the
.I
info
file.
.RE
.RS
8: unable to unset the exec-on-close bit on a temporary file.
.RE
.RS
9: multilib has not been set up (where required).
.RE
.RS
10:
.B
convertpkg-compat32
exited non-zero.
.RE
.RS
11: the
.B
convertpkg-compat32
script cannot be found (where required).
.RE
.SH BUGS
.P
None known. If found, Issues and Pull Requests to
.UR https://github.com/pghvlaans/sbotools/
.UE
are always welcome.
.SH SEE ALSO
.P
sbocheck(1), sboclean(1), sboconfig(1), sbofind(1), sboremove(1), sbosnap(1), sboupgrade(1), sbotools.conf(5)
.SH AUTHORS
.P
Jacob Pipkin <j@dawnrazor.net>
.P
Luke Williams <xocel@iquidus.org>
.P
Andreas Guldstrand <andreas.guldstrand@gmail.com>
.SH MAINTAINER
.P
K. Eugene Carlson <kvngncrlsn@gmail.com>
