.TH sboremove 1 "Pungenday, Discord 5, 3191 YOLD - Mojoday" "sbotools 3.5_RC" sbotools
.SH NAME
.P
.B
sboremove
- remove packages installed from SlackBuilds
.SH SYNOPSIS
.P
sboremove [-h|-v]
.P
sboremove [-a] sbo_name (sbo_name)
.SH DESCRIPTION
.P
.B
sboremove
removes packages installed from SlackBuilds, along with
any unneeded dependencies. Dependency information is
pulled recursively from
.I
info
files and honors the contents of
.B
sbotools.hints(5)\fR\
\&; any dependencies
that are required by no other installed SlackBuilds are eligible
for removal as well.
.B
sboremove
does not handle blacklisted scripts. If
.B
sboremove
is called with the
.B
--alwaysask
flag, the dependency requirements of other installed SlackBuilds
are not checked.
.P
In all cases, this script prompts the user package-by-package
before performing any removal operations. No option exists to enable
.B
sboremove
to uninstall packages without confirmation prompts,
and there are no plans to add that functionality in the
future.
.P
Root privileges are required to run
.B
sboremove\fR\
\&. If an invalid configuration is detected in
.I
/etc/sbotools/sbotools.conf\fR\
\&, or if invalid options are specified, the script
exits with a diagnostic message.
.SH OPTIONS
.P
.B
-h|--help
.RS
Show help information.
.RE
.P
.B
-v|--version
.RS
Show version information.
.RE
.P
.B
-a|--alwaysask
.RS
Always ask to remove dependencies, even if they are
required by other packages installed to the system.
.RE
.SH EXIT CODES
.P
.B
sboremove
can exit with the following codes:
.RS

0: all operations completed successfully.
.RE
.RS
1: a usage error occurred, such as running
.B
sboremove
with nothing to remove.
.RE
.RS
13: circular dependencies detected.
.SH BUGS
.P
None known. If found, Issues and Pull Requests to
.UR https://github.com/pghvlaans/sbotools/
.UE
are always welcome.
.SH SEE ALSO
.P
sbocheck(1), sboclean(1), sboconfig(1), sbofind(1), sbohints(1), sboinstall(1), sboupgrade(1), sbotools.conf(5), sbotools.hints(5)
.SH AUTHORS
.P
Luke Williams <xocel@iquidus.org>
.P
Jacob Pipkin <j@dawnrazor.net>
.P
Andreas Guldstrand <andreas.guldstrand@gmail.com>
.SH MAINTAINER
.P
K. Eugene Carlson <kvngncrlsn@gmail.com>
