.TH sboremove 1 "Pungenday, Aftermath 11, 3190 YOLD" "sbotools3 1.0" sbotools3
.SH NAME
.P
.B
sboremove
- remove packages installed from SlackBuilds
.SH SYNOPSIS
.P
sboremove [-h|-v]
.P
sboremove [-a] sbo_name (sbo_name)
.SH DESCRIPTION
.P
.B
sboremove
removes packages installed from SlackBuilds, along with
any unneeded dependencies. Dependency information is
pulled recursively from .info files; any dependencies
that are required by no other SlackBuilds will be eligible
for removal as well. If
.B
sboremove
is called with the
.B
--alwaysask
flag, the dependency requirements of other installed SlackBuilds
will not be checked.
.P
In all cases, this script prompts the user package-by-package
before performing any removal operations. No option exists to enable
.B
sboremove
to uninstall packages without confirmation prompts,
and there are no plans to add such a feature in the
future.
.SH OPTIONS
.P
-h|--help
.RS
Show help information.
.RE
.P
-v|--version
.RS
Show version information.
.RE
.P
-a|--alwaysask
.RS
Always ask to remove dependencies, even if they are
required by other packages installed to the system.
.RE
.SH EXIT CODES
.P
.B
sboremove
can exit with the following codes:
.RS

0: all operations completed successfully.
.RE
.RS
1: a usage error occurred, such as running sboremove with nothing to remove.
.RE
.SH BUGS
.P
None known. If found, Issues and Pull Requests to
.I
https://github.com/pghvlaans/sbotools3/
are always welcome.
.SH SEE ALSO
.P
sbocheck(1), sboclean(1), sboconfig(1), sbofind(1), sboinstall(1), sbosnap(1), sboupgrade(1), sbotools.conf(5)
.SH AUTHORS
.P
Luke Williams <xocel@iquidus.org>
.P
Jacob Pipkin <j@dawnrazor.net>
.P
Andreas Guldstrand <andreas.guldstrand@gmail.com>
.SH MAINTAINER
.P
K. Eugene Carlson <kvngncrlsn@gmail.com>
