.TH sbosnap 1 "Prickle-Prickle, The Aftermath 62, 3190 YOLD" "sbotools 3.2.1" sbotools
.SH NAME
.P
.B
sbosnap
-
backwards compatibility wrapper for sbocheck
.SH DESCRIPTION
.P
.B
sbosnap
was removed as an indepedent script in
.B
sbotools-3.3\fR\
\&. It is a compatibility symlink to
.B
sbocheck(1)\fR\
\&; the
.B
update
and
.B
fetch
options have no effect.
.SH SEE ALSO
.P
sbocheck(1), sboclean(1), sboconfig(1), sbofind(1), sboinstall(1), sboremove(1), sboupgrade(1), sbotools.conf(5), sbotools.hints(5)
.SH AUTHORS
.P
Jacob Pipkin <j@dawnrazor.net>
.P
Luke Williams <xocel@iquidus.org>
.P
Andreas Guldstrand <andreas.guldstrand@gmail.com>
.SH MAINTAINER
.P
K. Eugene Carlson <kvngncrlsn@gmail.com>
