.TH sbotools 1 "Setting Orange, Bureaucracy 21, 3191 YOLD" "sbotools 3.8.1" sbotool
.SH NAME
.P
.B
sbotool
- text user interface to sbotools
.SH SYNOPSIS
sbotool [-h|-v]

sbotool [-d FILE]
.SH DESCRIPTION
.B
sbotool
is a meta-tool providing a TUI to all of the
.B
sbotools
based on
.B
dialog(1)\fR\
\&. It can be run by root and non-root users. The contents of the menus
are dynamic and reflect available and efficacious options.
.B
sbotool
must be run as root (preferably in a login shell reached from e.g.
.B
su -\fR\
\&) to perform package installations, upgrades and removals, and to
fetch the repository. Use the
.B
Help
buttons in
.B
sbotool
for more information about individual menus.
.P
The basic workflow is straightforward: navigate to a script with
.B
Browse Repository
or
.B
Package Search
and choose from the list of options in the
.B
Operations
menu. Installed, upgradable
and override scripts can be reached from
.B
Installed\fR\
\&,
.B
Upgradable
and
.B
Overrides\fR\
\&,
respectively.
.B
Main Menu
has options for large-scale upgrades, rebuilds and shared object dependency
checks.
.P
.B
sbotools
calculates dependencies automatically, and individual scripts can be added
to the blacklist or have optional dependencies specified using the script's
.B
Hints
interface. Installations and upgrades can be performed either interactively
or non-interactively. If the non-interactive
.I
batch mode
can be offered,
.B
sbotool
displays a dry run on the confirmation screen. To specify build options for a
particular script, install interactively or use
.B
Build Options
from the script menu screen ahead of time as root. Build options are saved in the
.I
/var/log/sbotools
directory for future use.
.P
Individual scripts can be added to lists for installation, upgrade and removal
as the root user.
Any user may add to the template list; the template produced can be implemented as root
with
.B
sboinstall --use-template\fR\
\&.
Use
.B
List Operations
from
.B
Main Menu
to do the chosen operation for the listed scripts. These lists do not persist when
.B
sbotool
is closed. List operations use dependency resolution.
.P
If package operations are performed or
.B
sbotools
settings are changed from outside of
.B
sbotool
while the program is running, use the
.B
Refresh
option in the main menu to ensure that the output reflects these changes.
.P
Although most
.B
sbotools
operations can be accomplished in
.B
sbotool\fR\
\&, calling the scripts individually from the command line provides
superior efficiency and fine-tuned option control to experienced users.
See the
.B
Man Pages
menu to read further user documentation.
.SH STARTUP
Ensure that the terminal window is at least 80x25 characters to run
.B
sbotool\fR\
\&. The
.B
lines
and
.B
cols
terminal capabilities are required;
.B
tput(1)
can be used to check. This should not be a problem for any remotely
modern terminal.
.P
A copy of the
.I
SlackBuilds.org
repository must be fetched when using
.B
sbotools
for the first time, or when the
.B
sbotools
directory has been changed. Run
.B
sbotool
as root and select the
.B
Fetch Repository
option. The local repository is saved to
.I
/usr/sbo/repo
by default; the default upstream is the
.I
SlackBuilds.org
.B
GitLab
mirror, or the
.B
Ponce repository
for Slackware -current.
.P
.B
sbotools
has a number of potentially useful configuration
settings, including the upstream repository, git branch
and location. To make changes, run
.B
sbotool
as root and enter the
.B
Settings
menu. Select a setting from the list to see an
explanation and enter a new value. All configuration
values are documented in
.B
sbotools.conf(5)\fR\
\&.
.P
.B
sbotool
uses
.B
dialog(1)
for output. The color scheme and appearance can be
changed using a
.I
dialogrc
file. Set the
.B
DIALOGRC
setting to an
.B
absolute file path
to use an alternative
.I
dialogrc\fR\
\&. See
.I
/etc/dialogrc
or
.I
/usr/share/sbotools
for an example, or run
.RS

dialog --create-rc FILE


.RE
to generate a default
.I
dialogrc
to modify. The
.B
--dialogrc
option can also specify a file at runtime.
.SH OPTIONS
.B
-d|--dialogrc (FILE)
.RS
Use this dialogrc file for the current run of
.B
sbotool\fR\
\&. Overrides the
.B
DIALOGRC
setting.
.RE
.P
.B
-h|--help
.RS
Show help information.
.RE
.P
.B
-v|--version
.RS
Show version information.
.RE
.SH BUGS
None known. If found, Issues and Pull Requests to
.UR https://github.com/pghvlaans/sbotools/
.UE
are always welcome.
.SH SEE ALSO
.P
sbocheck(1), sboclean(1), sboconfig(1), sbofind(1), sbohints(1), sboinstall(1), sboremove(1), sboupgrade(1), sbotools(1), sbotools.colors(5), sbotools.conf(5), sbotools.hints(5), dialog(1), tput(1)
.SH AUTHORS
.P
Jacob Pipkin <j@dawnrazor.net>
.P
Luke Williams <xocel@iquidus.org>
.P
Andreas Guldstrand <andreas.guldstrand@gmail.com>
.SH MAINTAINER
.P
K. Eugene Carlson <kvngncrlsn@gmail.com>
