# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: sbotools3
subtitle: A ports-like interface to slackbuilds.org.
email:
description: >- # this means to ignore newlines until "baseurl:"
  sbotools3 is the continuation of sbotools. It is a
  ports-like interface to slackbuilds.org written in
  Perl.
minimal_mistakes_skin: default
search: false
copyright: K. Eugene Carlson
minimal_mistakes_skin: air

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

include:
  - man
  - downloads
  - development

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-include-cache

footer:
  links:
    - label: "sbotools3 on GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/pghvlaans/sbotools3/"

atom_feed:
  hide: true

defaults:
  # root directory
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      title: false
  # ChangeLog
  - scope:
      path: "/ChangeLog.html"
      type: pages
    values:
      layout: man
      author_profile: false
      title: false
  # man
  - scope:
      path: "man"
      type: pages
    values:
      layout: man
      author_profile: false
      title: false
  # downloads
  - scope:
      path: "downloads"
      type: pages
    values:
      layout: single
      author_profile: false
      title: false
  # development
  - scope:
      path: "development"
      type: pages
    values:
      layout: single
      author_profile: false
      title: false
