#!/usr/bin/perl
#
# vim: ts=2:et
#
# sbocutleaves
# script to remove leaf packages.
#
# authors: Jacob Pipkin <jacob.pipkin@icloud.com>
# maintainer: K. Eugene Carlson <kvngncrlsn@gmail.com>
# license: MIT License

use 5.16.0;
use strict;
use warnings FATAL => 'all';
use SBO::Lib qw/ :config :colors $descriptions_generated get_all_available get_installed_packages get_requires in lint_sbo_config on_blacklist prompt show_version slackbuilds_or_fetch usage_error wrapsay wrapsay_color /;
use File::Basename;
use Getopt::Long qw/ :config no_ignore_case_always bundling /;

my $self = basename($0);

sub show_usage {
  print <<"EOF";
Usage: $self [options] [sbo ...]
       $self [-l]

Options:
  -h|--help:
    this screen.
  -v|--version:
    version information.
  --(no)color:
    (do not) use sbotools color output.
  --(no)wrap:
    (do not) wrap sbotools output.
  -l|--list:
     list packages without reverse dependencies and exit.
  --raw:
     like --list, but space-delineated with no other formatting.
EOF
    return 1;
}

my ($help, $vers, $list, $raw, $color, $nocolor, $nowrap, $wrap);

my $options_ok = GetOptions(
  'help|h'       => \$help,
  'version|v'    => \$vers,
  'list|l'       => \$list,
  'raw'          => \$raw,
);

if ($help) { show_usage(); exit 0 }
if ($vers) { show_version(); exit 0 }
unless ($< == 0 or $list or $raw) {
  show_usage();
  usage_error "\nNon-root users can call $self with -l and --raw.";
}
unless ($options_ok) {
  show_usage();
  usage_error "\nOne or more invalid options detected.";
}

$config{COLOR} = $color ? 'TRUE' : 'FALSE' if $color xor $nocolor;
$config{NOWRAP} = $nowrap ? 'TRUE' : 'FALSE' if $wrap xor $nowrap;
lint_sbo_config($self, %config);

$list = $raw ? $raw : $list;

slackbuilds_or_fetch();
get_all_available();

my @seen;

CUTLEAVES:

my @installed = @{get_installed_packages("SBO", 1)};
my $installed_pkg = +{ map {; $_->{name}, $_->{pkg} } @installed };

my @delete = ();
my @leaves = ();

for my $sbo (sort keys %$installed_pkg) {
    next if in $sbo, @seen;
    next if on_blacklist $sbo and not $list;
    my $found = 0;
    for my $pkg (keys %$installed_pkg) {
        next if $pkg eq $sbo;
        if (in $sbo, @{get_requires($pkg)}) {
          ++$found;
          last;
        }
    }
    next if $found;

  if ($list) {
    push @leaves, $sbo;
  } else {
    wrapsay_color $color_warn, "Package: $sbo";
    if (prompt($color_default, "Mark $sbo for removal?", default => 'no')) {
        push @delete, $sbo;
        wrapsay_color $color_warn, "Marking $sbo for removal.";
    } else {
        wrapsay_color $color_default, "Keeping $sbo.";
    }

    say "";

    push @seen, $sbo;
  }
}

if ($raw) {
  exit 0 unless @leaves;
  print "$_ " for (sort @leaves);
  exit 0;
}
if ($list) {
  exit 0 unless @leaves;
  wrapsay_color $color_notice, "The following packages have no installed reverse dependencies:";
  for (sort @leaves) {
    my $line = $_;
    $line = on_blacklist($_) ? "$line (blacklisted)" : $line;
    print "  $line\n";
  }
  exit 0;
}

exit 0 if @delete == 0;

wrapsay_color $color_warn, "Done. The following packages are marked for removal:";
print "  $_\n" for (sort @delete);
say "";
exit 0 unless prompt($color_warn, "Proceed with removal?", default => 'no');
system("/sbin/removepkg", $_) for @delete;

say "";
exit 0 unless prompt($color_notice, "Go on with new leaf packages?", default => 'yes');

goto CUTLEAVES;

END { say "" if not $raw; }
